import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Template } from '../domain/models/Template'
import type { SetupMetadata } from '../repositories/LocalMetadataRepository'
import { TemplateService } from '../services/TemplateService'

const templateService = new TemplateService()
const categories = ['baptism', 'confirmation', 'communion', 'marriage', 'anointing', 'funeral', 'general']

export function TemplatesPage({ setup }: { setup: SetupMetadata }) {
  const [templates, setTemplates] = useState<Template[]>([])
  const [category, setCategory] = useState('general')
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [file, setFile] = useState<File>()
  const [previewUrl, setPreviewUrl] = useState('')
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { templateService.load().then(setTemplates).catch(() => setError('The local templates folder could not be read. Reconnect it and try again.')) }, [])
  const upload = async () => { if (!file || !name.trim()) { setError('Choose a file and enter a template name.'); return }; if (!['application/pdf', 'image/png', 'image/jpeg'].includes(file.type)) { setError('Only PDF, PNG, and JPG templates are supported for this first version.'); return }; const template: Template = { id: crypto.randomUUID(), parishId: setup.parish.id, name: name.trim(), category, fileType: file.type, fileName: `${crypto.randomUUID()}-${file.name}`, description, version: '1', createdAt: new Date().toISOString(), active: true }; try { await templateService.upload(file, template); const next = [...templates, template]; await templateService.save(setup, next); setTemplates(next); setName(''); setDescription(''); setFile(undefined); setMessage('Template stored in the local parish folder.'); } catch { setError('The template could not be stored. The original local files were left untouched.') } }
  const openTemplate = async (template: Template, download = false) => { try { const blob = await templateService.read(template); const url = URL.createObjectURL(blob); if (download) { const anchor = document.createElement('a'); anchor.href = url; anchor.download = template.fileName; anchor.click() } else { setPreviewUrl(url) } } catch { setError('The template file is unavailable. Check the local templates folder.') } }
  const remove = async (template: Template) => { if (!window.confirm(`Delete ${template.name}? This removes the local template file.`)) return; try { await templateService.remove(template); const next = templates.filter((item) => item.id !== template.id); await templateService.save(setup, next); setTemplates(next); setMessage('Template deleted locally.') } catch { setError('The template could not be deleted. It was left unchanged.') } }
  return <main className="workspace-page"><header className="topbar"><Link className="brand" to="/dashboard">Parish <span>System</span></Link><Link className="text-button" to="/dashboard">Back to dashboard</Link></header><div className="people-shell"><div className="dashboard-heading"><div><p className="eyebrow">Forms and templates</p><h1>Parish templates.</h1><p className="step-detail">Store each parish's official forms locally. Nothing is uploaded to a central service.</p></div></div><section className="people-grid"><div className="people-list">{templates.length === 0 && <div className="empty-state"><strong>No templates yet.</strong><span>Upload the first local parish form using the form.</span></div>}{templates.map((template) => <div className="person-row" key={template.id}><div className="avatar">{template.fileType.includes('pdf') ? 'PDF' : 'IMG'}</div><div className="person-identity"><strong>{template.name}</strong><span>{template.category} · {template.fileName}</span></div><button className="text-button" onClick={() => void openTemplate(template)}>Preview</button><button className="text-button" onClick={() => void openTemplate(template, true)}>Download</button><button className="text-button danger-text" onClick={() => void remove(template)}>Delete</button></div>)}</div><div className="people-form"><p className="eyebrow">Upload template</p><h2>Add a local form.</h2><div className="form-grid"><label className="wide-field">Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Baptism certificate" /></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label className="wide-field">Description<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="wide-field">File<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0])} /></label></div><button className="button button-primary" onClick={() => void upload()}>Store template locally <span aria-hidden="true">→</span></button><p className="form-note">Supported now: PDF, PNG, and JPG. DOCX storage can be added later without pretending to edit it in-browser.</p></div></section>{previewUrl && <section className="template-preview"><button className="text-button" onClick={() => { URL.revokeObjectURL(previewUrl); setPreviewUrl('') }}>Close preview</button><iframe title="Template preview" src={previewUrl} /></section>}{error && <p className="error-message" role="alert">{error}</p>}{message && <p className="success-message">{message}</p>}</div></main>
}
